---
title: "SURE EDA Project"
author: "Akwellé (Q) Quaye"
date: '2022-06-14'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
medicare <- read_csv("http://www.stat.cmu.edu/cmsac/sure/2022/materials/data/health/eda_projects/medicare_partd_presc_claims.csv")
```


#avg claims per state, by opioid flag


```{r}
populations_2019 <- read_csv("/Users/Akwelle/Desktop/SURE 22/SURE EDA Project/state-populations-2019.csv")

populations_2019 <- as.vector(populations_2019$population)

avgNumClaims <- medicare %>%
  group_by(state = State, opioid = OpioidFlag) %>%
  summarize(sumNumberClaims = sum(NumberClaims))

avgNumClaims$population <- populations_2019

avgNumClaims_n <- avgNumClaims %>%
  mutate(numClaimsPer10000 = sumNumberClaims / population * 10000)

plot_colors = rep(c("Non-Opioid", "Opioid"), times=51)
  
avgNumClaims_n %>%
  ggplot(aes(x = opioid, y=numClaimsPer10000)) +
  geom_bar(stat="identity",aes(fill=plot_colors)) +
  labs(x = NULL, y = "Average Inusrance Claim Per Provider") +
  facet_wrap(~ state) +
  theme_minimal() +
  scale_fill_discrete(name="Prescription Type") +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position="bottom")


```
# average claims per state with non-opioids removed

``` {r}
opioidOnly <-  avgNumClaims_n %>%
  filter(opioid == "Opioid")



opioidOnly %>%
  ggplot(aes(x = reorder(state, -numClaimsPer10000), y=numClaimsPer10000)) +
  geom_bar(stat="identity", fill='lightblue') +
  labs(title = "Opioid Prescription Claims per 10,000 Residents in the United States",
       x = "State", y= "Claims for Opioid Prescriptions (per 10000)") +
  theme_minimal()

```

#scatterplot of opioid claims per 10000 v. population

```{r}
library(ggrepel)


opioidOnly %>%
  ggplot(aes(x=population, y=numClaimsPer10000, label=state)) +
  geom_text_repel(color="red", size=2) +
  scale_color_viridis_c() +
  labs(x = "State Population", y="Opioid Prescription Claims per 10,000 residents",
       main="Opioid Prescription Claims by State") +
  geom_point() +
  theme_minimal()
```

#usmap of above data

```{r}
library(usmap)

opioidOnly <- medicare %>%
  filter(OpioidFlag == "Opioid") %>%
  group_by(state = State) %>%
  summarize(meanNumClaims = mean(NumberClaims))



plot_usmap(data=opioidOnly, values="meanNumClaims", color='red') +
  scale_fill_continuous(low="darkblue", high="darkorange", name="Average Opioid Claim Per Provider")


```







